### ISSUE TITLE
Production Checklist

### ISSUE THREAD

**Issue by lovethebomb** [Low3nd/mancini-lawyer#1]
### CONTENT

- [ ]   All text free from spelling errors
- [x]   Page and content formatting appropriate on all pages
- [ ]   Placeholder text removed
- [x]   All pages have content
- [ ]   ~~Privacy Policy included (Generate one at [getterms.io](http://getterms.io/))
- []   ~~Print stylesheet exists and tested~~
- [x]   Favicon created and displays correctly (retina included)
- [x]   Device icons created and display correctly
- [x]   Footer includes copyright statement
- [x]   404 page exists and informative
- [x]   Correct author is attributed to pages and posts (as required)

### SEO & ANALYTICS

- [x]   Page titles are descriptive and SEO friendly
- [x]   All page titles are unique
- [x]   Meta data included and appropriate
- [x]   H1s used for page titles and only one H1 per page
- [ ]   XML sitemap has been generated and added to root of website
- [x]   robots.txt is generated and added to root of website
- []   ~~301 redirects for existing website are prepared and in place~~
- [x]   Website can be accessed by search engines (remove noindex, nofollow for pages) 
- []   ~~Google Analytics and relevant analytics/tracking tools installed~~
- [x] Check for canonical domain issues (e.g. variations in links to [http://site.com](http://site.com/) [http://www.site.com](http://www.site.com/) [http://www.site.com/index.html](http://www.site.com/index.html) should be reduced to a single consistent style)
- [ ] Add website on Search Console

### SOCIAL

- [x] Open Graph tags included across website and appropriate? (including images where possible)
- [x] Social accounts integrated, linking to correct URLs and use API for integrations

### MARKUP

- [x]   ~~HTML has passed validation (or known issues noted)~~
- [x]   ~~CSS has passed validation (or known issues noted)~~
- [x]   ~~Bonus: CSS tested on [CSS Lint](http://csslint.net/) (to hurt your feelings)~~
- [x]   Site links have been tested and resolve correctly
- [x]   JavaScript is error free

### ACCESSIBILITY

- [x]   Website meets appropriate level of WCAG compliance
- [x]   ARIA Landmark Roles specified
- [x]   Semantic headings and structure used
- [x]   Links are clearly recognisable and have :focus state
- [x]   Images use appropriate ALT text
- [x]   Alternatives provided for users with Javascript disabled
- [x]   Forms have logical layout
- [x]   Associated label for all form controls
- [x]   Colour contrast tested
- [ ]   Website accessibility has been checked with Total Validator Pro or [WAVE](http://wave.webaim.org/) and issues resolved (exceptions noted)

### OPTIMISATION

- [x]   Images have been optimised
- [x]   CSS is minified and combined
- [x]   JavaScript is minified and combined (as much as possible)
- [x]   Enable gzip compression
- [x]   Ensure only necessary fonts, weights and character sets are installed
- [ ]   Run [Google speed test](https://developers.google.com/speed/pagespeed/insights/) and optimise accordingly (record score and known issues)
- [ ]   Run [Web page test](http://www.webpagetest.org/) and optimise accordingly (record results)
- []   ~~Incorporate CDN / Caching as required~~

### POST LAUNCH

- [ ]   Ensure site is visible to search engines
- [ ]   SSL certificates successfully installed
- [ ]   Images, media and links reference live URL
- [ ]   Webfonts integrated and working correctly on live site
- [ ]   ~~Webfonts set to production (as required)~~
- [ ]   ~~301 redirects are in place and working correctly~~
- [ ]   ~~Website URL has been [submitted](https://www.google.com/webmasters/tools/submit-url?pli=1) to Google~~
- [x]   Generate a new sitemap.xml and upload to root
- [ ]   ~~Analytics has been setup and integrated into website~~
